### ISSUE TITLE
null values

### ISSUE THREAD

**Issue by rogueturnip** [arg-def/mapper-js#1]
First want to say this is a really great library!  It's helped alot with one of our projects.

One question.  When assigning a value, is there a way to prevent it from creating the new mapping if the mapped object is null or undefined?

**Comment by themgoncalves** [comment]
Hi @rogueturnip, could you please give a *code example* of the desired result? It will help to clarify the requirements.

Cheers!

**Comment by rogueturnip** [comment]
Thanks for responding!  What I'd like to see is for a mapping like this:
    const mapping = mapper.mapping(map => ({
      deviceId: map.get("raw.deviceId").value,
    }));

If the value for raw.deviceId is null or undefined it would not create the deviceId.  If the item was nested ("something.else": map.get("something").value) it wouldn't create the parent(something).

To make sure that it's possible to create ones that do need the null to be present, returning null in the .transform would create the null item.

    const mapping = mapper.mapping(map => ({
      deviceId: map.get("raw.deviceId").transform(([value])=>return null).value,
    }));

Does this help?

**Comment by themgoncalves** [comment]
@rogueturnip thanks for the explanation! Also, if I may ask, what is the value that it brings? Especially comparing that you can remove the `falsy entries` by running, e.g:

```
const cleanObj = obj =>Object.keys(obj).reduce((acc, key) => {
  if (Boolean(obj[key])) {
    acc[key] = obj[key];
  }

  return acc;
}, {});
``` 

As I need to assert the best approach to this problem.

Cheers!

**Comment by rogueturnip** [comment]
I had a couple of scenarios.
1. the value to translate doesn't exist in the json being converted.  This resulted with a null
2. the value to translate is null or undefined, the result matched

I did what you have as an example but with a recursive function because I could get the null removed at the lowest level but the parent objected ended up as {}.

As example, if I was translating parent.child.something and something didn't exist or was null I would get 
parent: {
  child: {}
}

Hope this helps.

**Comment by themgoncalves** [comment]
Thanks for the clarifications @rogueturnip, I will be working on a new feature with this requirement.

**Comment by themgoncalves** [comment]
@rogueturnip just _released_ `v0.1.3` with the new _mapping options_, take a look in the [documentation for more details](https://github.com/arg-def/mapper-js#mapper-options).

### preview:

#### With global options

```js
/* source object
{
  person: {
    name: 'John',
    lastName: 'Doe',
    age: 32,
  },
}
*/
const mapping = mapper.mapping((map) => ({
  'name': map.get('person.name').value,
  'age': map.get('person.age').value,
   // source doesn't have propery 'address',
   // therefore will return "undefined"
  'address': map.get('person.address').value,
}));

mapper(source, mapping, { suppressNullUndefined: true } );
/* outputs 
{
  name: 'John',
  age: 32,
}
*/
```


#### With single case options

This option _overrides_ the _global definitions_.

```js
/* source object
{
  person: {
    name: 'John',
    lastName: 'Doe',
    age: 32,
  },
}
*/
const mapping = mapper.mapping((map) => ({
  'name': map.get('person.name').value,
  'age': map.get('person.age').value,
   // source doesn't have propery 'address',
   // therefore will return "undefined" for both entries right bellow
  'address': map.get('person.address[0]').value,
  // we flag to suppress the entry bellow if the result is null or undefined
  'business': map.get('person.address'[1],  { suppressNullUndefined: true }).value,
}));

mapper(source, mapping);
/* outputs 
{
  name: 'John',
  age: 32,
  address: undefined,
}
*/
```

**Comment by rogueturnip** [comment]
This is excellent!  I'm actually just doing some new code with the mapper so I can probably get some testing of it done today and let you know if anything comes up.

Thanks for making this addition.  Lots of potential to your module!
